### ISSUE TITLE
NMFS Open Science logo should be more inclusive

### ISSUE THREAD

**Issue by jmlondon** [nmfs-opensci/.github#1]
I really like the idea of a logo specific for our NMFS Open Science community/mov't. But, the current logo only includes fish and we want to make sure all of the taxa, fields, etc within NMFS are represented.

I'm not sure from a graphic design sense what an improvement would look like. One option would be to just 'add more species' to the logo -- at least one whale, one pinniped, and one turtle. But, it could get over-crowded and we'd still end up leaving some out. Maybe we need to think about something more symbolic of ocean/ecosystems?

I could also reach out to our graphics design folks here at AFSC for ideas -- as long as that would be ok with whoever created the current logo.

**Comment by eeholmes** [comment]
![imageedit_87_2356199673](https://user-images.githubusercontent.com/2545978/183321168-65c1800f-e470-4009-835d-341bbe5f77d9.gif)

**Comment by eeholmes** [comment]
![open-logo](https://user-images.githubusercontent.com/2545978/183321277-16394e58-0a30-4b51-bfb3-09ea2aee1860.png)

**Comment by eeholmes** [comment]
I tried a putting more critters on it but it looked really busy. I was trying to 'riff' on this image. 
![image](https://user-images.githubusercontent.com/2545978/183321493-c692652b-88e0-4ca5-ba47-9b7ce364bd8b.png)

**Comment by eeholmes** [comment]
![imageedit_124_5910423886](https://user-images.githubusercontent.com/2545978/183326545-9cba8920-daf2-4c98-8a60-58e9067fad5a.png)

**Comment by eeholmes** [comment]
I am leaning towards generic until I/we have time to work on a better cartoon that represents NMFS work more inclusively. Here is one with NOAA color palette.

![nmfs-open-sci-transparent](https://user-images.githubusercontent.com/2545978/183424389-bfca6823-d3bd-4f32-9c59-d6ea2471bc20.png)

**Comment by eeholmes** [comment]
or one of these. NOAA palette and riffing on xyzOpenSci seen for other groups. The first text colors mimics how in NOAA Fisheries, NOAA is dark blue and Fisheries is light blue. My favorite is the first one. Simple yet relates to NOAA Fisheries via the the palette.
![imageedit_146_2259263971](https://user-images.githubusercontent.com/2545978/183430385-7190e113-a410-4f0d-b1ea-f2e7dab50bc2.png)

![imageedit_136_4950328219](https://user-images.githubusercontent.com/2545978/183430419-19e78624-f339-45a3-8d13-267b4a352965.png)

**Comment by jmlondon** [comment]
How about this? Just a first idea so open to other ideas ... inspired by old school NMFS and keeping the open circle theme @eeholmes started riffing with. I always liked how the old school nmfs logo silhouettes did a good job of representing fish, seals, whales, etc in a stylistic manner. I just re-worked it into a circle and, then, added the open circle concept around it.
  
<img width="724" alt="Screen Shot 2022-08-08 at 10 47 19 AM" src="https://user-images.githubusercontent.com/513923/183481213-af304597-c6fa-48cf-b56f-1ad01d59f02a.png">

**Comment by jmlondon** [comment]
here, with text
<img width="1393" alt="Screen Shot 2022-08-08 at 11 58 15 AM" src="https://user-images.githubusercontent.com/513923/183493461-ccd3eb84-9caf-4383-917c-71aaefa6d623.png">

**Comment by eeholmes** [comment]
That looks nice too! The upside down C has been appearing in open science logos. But it is kind of hard to get things to fit with that.  and it admittedly is kind of clunky

<img width="292" alt="image" src="https://user-images.githubusercontent.com/2545978/183500955-02a56487-3d78-47f7-9a61-b22e1a873597.png">

**Comment by eeholmes** [comment]
![image](https://user-images.githubusercontent.com/2545978/183503832-3053ea8e-228f-46bc-bded-249ef9a2e35a.png)

**Comment by jmlondon** [comment]
ha ... I didn't even recognize it as an upside down C. I thought it was a person in the middle of a circle. Or, represented an opening in the letter O. And, I'm not sure what it's supposed to mean ... C for community?

From a design perspective, I find having the opening at the bottom disrupts the flow and is atypical of logo design. With the opening on the right, it aligns where the silhouettes come together and, then, flows right into the word OPEN. Symbolizes agency scientists coming together to explore open science.

**Comment by jmlondon** [comment]
this text/font is, I think, more consistent with agency branding

<img width="1325" alt="Screen Shot 2022-08-08 at 1 21 09 PM" src="https://user-images.githubusercontent.com/513923/183507414-680283ba-b5b1-419a-a2ca-7f08821aaddc.png">
